services:
 
  # -------------------------------------------------------------------
  # Speaches TTS server
  # -------------------------------------------------------------------
  speaches:
    image: ghcr.io/speaches-ai/speaches:0.8.0-rc.2-cpu   # replace with the correct Speaches image if yours is different
    container_name: speaches
    restart: unless-stopped  
    ports:
      - "8000:8000"                            # Speaches serves on 8000/v1/audio/speech
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN:-""}
      - KOKORO_REVISION=c97b7bbc3e60f447383c79b2f94fee861ff156ac
      - SPEACHES_NO_AUTH=1
      - LOG_LEVEL=debug
      - SPEACHES_API_KEY=speaches_api_key
      - OPENAI_BASE_URL=http://speaches:8000/v1/
      - OPENAI_API_KEY="speaches_api_key"
      - WHISPER__USE_BATCHED_MODE=true
      - WHISPER__COMPUTE_TYPE=float32
      - WHISPER__CPU_THREADS=6
      - CHAT_COMPLETION_BASE_URL=http://localhost:11434/v1
      - CHAT_COMPLETION_API_KEY=speaches_api_key
      - LOOPBACK_HOST_URL=http://0.0.0.0:8000
      - ENABLE_UI=false
      
    volumes:
      - hf-hub-cache:/root/.cache/huggingface/hub
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
      - ~/models:/app/models
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.multi
    #   target: api-build
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: LibreChat-API
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - rag_api
      - speaches
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - DEBUG=true
      - LOG_LEVEL=debug
      - OPENAI_BASE_URL=http://speaches:8000/v1/
      - OPENAI_API_KEY="speaches_api_key"
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
      - ./memory:/app/client/memory

  client:
    image: nginx:1.27.0-alpine
    container_name: LibreChat-NGINX
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    restart: always
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/slopchat.hddev.tech:/etc/letsencrypt/live/slopchat.hddev.tech
      - /etc/letsencrypt/archive/slopchat.hddev.tech:/etc/letsencrypt/archive/slopchat.hddev.tech
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.12:/meili_data
  vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env

volumes:
  pgdata2:
  hf-hub-cache: